version: '3.8'

services:
  node1:
    build:
      context: ../../DistributedRaft.Cluster
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - NODE_IDENTIFIER=node1
      - OTHER_NODE_URLS=http://node2:8080;http://node3:8080
    ports:
      - "5001:8080"

  node2:
    build:
      context: ../../DistributedRaft.Cluster
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - NODE_IDENTIFIER=node2
      - OTHER_NODE_URLS=http://node1:8080;http://node3:8080
    ports:
      - "5002:8080"

  node3:
    build:
      context: ../../DistributedRaft.Cluster
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5003
      - NODE_IDENTIFIER=node3
      - OTHER_NODE_URLS=http://node1:8080;http://node2:8080
    ports:
      - "5003:8080"
        
  gateway:
    build:
      context: ../../DistributedRaft.Gateway
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - CLUSTER_NODES=http://node1:8080;http://node2:8080;http://node3:8080
    ports:
      - "5000:8080"
