version: '3.8'

x-dotnet_sync: &dotnet_sync
  develop:
    watch:
      - action: sync
        path: ./app/DistributedRaft
        target: ./app/

x-node_base: &node_base
  build:
    context: ../../DistributedRaft.Cluster
    dockerfile: Dockerfile
    target: development
  <<: *dotnet_sync

x-node_environment: &node_environment
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080

services:
  node1:
    <<: *node_base
    environment:
      <<: *node_environment
      NODE_IDENTIFIER: node1
      OTHER_NODE_URLS: http://node2:8080;http://node3:8080
    ports:
      - "5001:8080"

  node2:
    <<: *node_base
    environment:
      <<: *node_environment
      NODE_IDENTIFIER: node2
      OTHER_NODE_URLS: http://node1:8080;http://node3:8080
    ports:
      - "5002:8080"

  node3:
    <<: *node_base
    environment:
      <<: *node_environment
      NODE_IDENTIFIER: node3
      OTHER_NODE_URLS: http://node1:8080;http://node2:8080
    ports:
      - "5003:8080"
  
  gateway:
    build:
      context: ../../DistributedRaft.Gateway
      dockerfile: Dockerfile
      target: development
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      CLUSTER_NODES: http://node1:8080;http://node2:8080;http://node3:8080
    ports:
      - "5010:8080"
