version: '3.8'

x-node_base: &node_base
  build:
    context: ../../DistributedRaft.Cluster
    dockerfile: Dockerfile
    target: runtime

x-node_environment: &node_environment
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080

services:
  node1:
    <<: *node_base
    environment:
      <<: *node_environment
      NODE_IDENTIFIER: node1
      OTHER_NODE_URLS: http://node2:8080;http://node3:8080

  node2:
    <<: *node_base
    environment:
      <<: *node_environment
      NODE_IDENTIFIER: node2
      OTHER_NODE_URLS: http://node1:8080;http://node3:8080

  node3:
    <<: *node_base
    environment:
      <<: *node_environment
      NODE_IDENTIFIER: node3
      OTHER_NODE_URLS: http://node1:8080;http://node2:8080
  
  gateway:
    build:
      context: ../../DistributedRaft.Gateway
      dockerfile: Dockerfile
      target: runtime
    environment:
      ASPNETCORE_URLS: http://+:8080
      CLUSTER_NODES: http://node1:8080;http://node2:8080;http://node3:8080
  
  swag:
    container_name: drew-raft-swag
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=demomusic801.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/drew/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:4321:443
    restart: unless-stopped
